apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: percona
spec:
  crVersion: 1.14.0
  secretsName: percona
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 50Gi
  haproxy:
    enabled: true
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
  logcollector:
    enabled: true
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
