apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack3.kcloud.zone
  cinder:
    volume:
      storage:
        rookCeph:
          clientName: openstack3-cinder
          poolName: openstack3-cinder-volumes
  glance:
    storage:
      rookCeph:
        clientName: openstack3-glance
        poolName: openstack3-glance-images
  nova:
    compute:
      nodeSelector:
        openstack/cloud: openstack3
  neutron:
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack3
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack3
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack3
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack3
