apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack3.kcloud.zone
  cinder:
    backends:
    - name: ceph
      volumeBackendName: ceph
      ceph:
        poolName: openstack3-cinder-volumes
        clientName: openstack3-cinder
        secret: cinder-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  glance:
    backends:
    - name: ceph-ssd
      ceph:
        poolName: openstack3-glance-images
        clientName: openstack3-glance
        secret: glance-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  nova:
    compute:
      nodeSelector:
        openstack/cloud: openstack3
  neutron:
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack3
