apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack3.kcloud.zone
  cinder:
    backends:
    - name: ceph-ssd
      volumeBackendName: ceph-ssd
      ceph:
        poolName: openstack3-cinder-volumes-ssd
        clientName: openstack3-cinder
        secret: cinder-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
    - name: ceph-hdd
      volumeBackendName: ceph-hdd
      ceph:
        poolName: openstack3-cinder-volumes-hdd
        clientName: openstack3-cinder
        secret: cinder-ceph
        rook:
          namespace: rook-ceph
          deviceClass: hdd
          replicatedSize: 2
  glance:
    backends:
    - name: ceph-ssd
      ceph:
        poolName: openstack3-glance-images
        clientName: openstack3-glance
        secret: glance-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  nova:
    compute:
      nodeSelector:
        openstack/cloud: openstack3
  neutron:
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack3
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack3
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack3
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack3
