apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cinder-storageclass.yaml
bases:
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/cinder-csi-plugin/csi-cinder-driver.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/controller-manager/cloud-controller-manager-roles.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.22.0/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
patchesJson6902:
- target:
    kind: DaemonSet
    version: v1
    name: openstack-cloud-controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --cluster-name=$(CLUSTER_NAME)
