
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-openstack-k8s-ianunruh-com-v1beta1-keystone
  failurePolicy: Fail
  name: mkeystone.kb.io
  rules:
  - apiGroups:
    - openstack.k8s.ianunruh.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keystones
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openstack-k8s-ianunruh-com-v1beta1-keystone
  failurePolicy: Fail
  name: vkeystone.kb.io
  rules:
  - apiGroups:
    - openstack.k8s.ianunruh.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keystones
  sideEffects: None
