# permissions for end users to view barbicans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: barbican-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - barbicans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - barbicans/status
  verbs:
  - get
