# permissions for end users to edit barbicans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: barbican-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - barbicans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - barbicans/status
  verbs:
  - get
