# permissions for end users to view cinders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinder-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - cinders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - cinders/status
  verbs:
  - get
