# permissions for end users to view glances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glance-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - glances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - glances/status
  verbs:
  - get
