# permissions for end users to edit heats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heat-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - heats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - heats/status
  verbs:
  - get
