# permissions for end users to edit horizons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizon-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - horizons/status
  verbs:
  - get
