# permissions for end users to view horizons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horizon-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - horizons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - horizons/status
  verbs:
  - get
