# permissions for end users to edit keystones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystone-editor-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones/status
  verbs:
  - get
