# permissions for end users to view keystones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystone-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones/status
  verbs:
  - get
