# permissions for end users to edit keystoneusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneuser-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - keystoneusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - keystoneusers/status
  verbs:
  - get
