# permissions for end users to view keystoneusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneuser-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneusers/status
  verbs:
  - get
