# permissions for end users to edit keystoneservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoneservice-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - keystoneservices/status
  verbs:
  - get
