# permissions for end users to view magnums.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magnum-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - magnums
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - magnums/status
  verbs:
  - get
