# permissions for end users to edit manilas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manila-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - manilas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - manilas/status
  verbs:
  - get
