# permissions for end users to view manilas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manila-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - manilas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - manilas/status
  verbs:
  - get
