# permissions for end users to edit mariadbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-editor-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbs/status
  verbs:
  - get
