# permissions for end users to view mariadbdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbdatabase-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbdatabases/status
  verbs:
  - get
