# permissions for end users to edit neutrons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neutron-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - neutrons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - neutrons/status
  verbs:
  - get
