# permissions for end users to view neutrons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neutron-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - neutrons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - neutrons/status
  verbs:
  - get
