# permissions for end users to edit novacells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novacell-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacells/status
  verbs:
  - get
