# permissions for end users to view nova.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nova-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas/status
  verbs:
  - get
