# permissions for end users to edit nova.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nova-editor-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas/status
  verbs:
  - get
