# permissions for end users to view novahostaggregates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novahostaggregate-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novahostaggregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novahostaggregates/status
  verbs:
  - get
