# permissions for end users to view novacomputes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novacompute-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novacomputes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novacomputes/status
  verbs:
  - get
