# permissions for end users to edit novaflavors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaflavor-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novaflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novaflavors/status
  verbs:
  - get
