# permissions for end users to edit novacomputes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novacompute-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacomputes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacomputes/status
  verbs:
  - get
