# permissions for end users to view novacomputesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novacomputeset-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacomputesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacomputesets/status
  verbs:
  - get
