# permissions for end users to edit novakeypairs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novakeypair-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novakeypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novakeypairs/status
  verbs:
  - get
