# permissions for end users to view novacells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novacell-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacells
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - novacells/status
  verbs:
  - get
