# permissions for end users to view octavia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octavia-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - octavias
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - octavias/status
  verbs:
  - get
