# permissions for end users to edit ovncontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncontrolplane-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - ovncontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - ovncontrolplanes/status
  verbs:
  - get
