# permissions for end users to view ovncontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncontrolplane-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - ovncontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - ovncontrolplanes/status
  verbs:
  - get
