# permissions for end users to edit placements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placement-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - placements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - placements/status
  verbs:
  - get
