# permissions for end users to view placements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placement-viewer-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - placements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - placements/status
  verbs:
  - get
