# permissions for end users to edit rabbitmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - rabbitmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - rabbitmqs/status
  verbs:
  - get
