# permissions for end users to edit rallies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rally-editor-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies/status
  verbs:
  - get
