# permissions for end users to view rallytasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rallytask-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallytasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallytasks/status
  verbs:
  - get
