# permissions for end users to view rallies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rally-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies/status
  verbs:
  - get
