# permissions for end users to edit rallytasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rallytask-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - rallytasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - rallytasks/status
  verbs:
  - get
