
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ceph.rook.io
  resources:
  - cephblockpools
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ceph.rook.io
  resources:
  - cephclients
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - barbicans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - barbicans/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - barbicans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - cinders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - cinders/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - cinders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - controlplanes/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - glances/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - glances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - heats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - heats/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - heats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - horizons/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - horizons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneservices/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneusers/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - keystoneusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - magnums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - magnums/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - magnums/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - manilas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - manilas/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - manilas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - mariadbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - neutrons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - neutrons/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - neutrons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novacells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novacells/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novacells/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - novas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - octavias
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - octavias/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - octavias/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - ovncontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - ovncontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - ovncontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - placements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - placements/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - placements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqs/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqusers/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rabbitmqusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - rallies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - senlins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - senlins/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - senlins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
