# permissions for end users to view senlins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senlin-viewer-role
rules:
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - senlins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k8s.ianunruh.com
  resources:
  - senlins/status
  verbs:
  - get
