# permissions for end users to edit senlins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senlin-editor-role
rules:
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - senlins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.ospk8s.com
  resources:
  - senlins/status
  verbs:
  - get
