apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-google
spec:
  acme:
    email: ianunruh@gmail.com
    privateKeySecretRef:
      name: letsencrypt-google-issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: ospk8s
          serviceAccountSecretRef:
            name: google-dns
            key: key
