## Append samples you want in your CSV to this file as resources ##
resources:
- openstack_v1beta1_controlplane.yaml
- openstack_v1beta1_mariadb.yaml
- openstack_v1beta1_mariadbdatabase.yaml
- openstack_v1beta1_keystone.yaml
- openstack_v1beta1_keystoneservice.yaml
- openstack_v1beta1_keystoneuser.yaml
- openstack_v1beta1_glance.yaml
- openstack_v1beta1_placement.yaml
- openstack_v1beta1_rabbitmq.yaml
- openstack_v1beta1_rabbitmquser.yaml
- openstack_v1beta1_nova.yaml
- openstack_v1beta1_novacell.yaml
- openstack_v1beta1_neutron.yaml
- openstack_v1beta1_memcached.yaml
- openstack_v1beta1_cinder.yaml
- openstack_v1beta1_magnum.yaml
- openstack_v1beta1_barbican.yaml
- openstack_v1beta1_ovncontrolplane.yaml
- openstack_v1beta1_octavia.yaml
- openstack_v1beta1_rally.yaml
- openstack_v1beta1_manila.yaml
- openstack_v1beta1_senlin.yaml
- openstack_v1beta1_rallytask.yaml
- openstack_v1beta1_novacompute.yaml
- openstack_v1beta1_novahostaggregate.yaml
- openstack_v1beta1_novakeypair.yaml
- openstack_v1beta1_novaflavor.yaml
- openstack_v1beta1_novacomputeset.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
