apiVersion: openstack.ospk8s.com/v1beta1
kind: Cinder
metadata:
  name: cinder
spec:
  api:
    image: kolla/cinder-api:2023.2-ubuntu-jammy
    replicas: 2
    ingress:
      host: cinder.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  backup:
    enabled: true
    image: kolla/cinder-backup:2023.2-ubuntu-jammy
  scheduler:
    image: kolla/cinder-scheduler:2023.2-ubuntu-jammy
    replicas: 2
  volume:
    image: kolla/cinder-volume:2023.2-ubuntu-jammy
  backends:
  - name: ceph-ssd
    volumeBackendName: ceph-ssd
    ceph:
      poolName: openstack-cinder-volumes
      clientName: openstack-cinder
      secret: cinder-ceph
      rook:
        namespace: rook-ceph
        deviceClass: ssd
        replicatedSize: 2
  database:
    name: cinder
    secret: cinder-db
    cluster: mariadb
  broker:
    name: cinder
    secret: cinder-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
