apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Keystone
metadata:
  name: keystone
spec:
  image: ianunruh/keystone:latest
  api:
    replicas: 2
    ingress:
      host: keystone.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: keystone
    secret: keystone-db
    cluster: mariadb
