apiVersion: openstack.ospk8s.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.k8s.example.com
  ingress:
    annotations:
      external-dns/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt
  nodeSelector:
    compute:
      openstack/cloud: openstack
      openstack/compute-node: enabled
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    api:
      image: kolla/keystone:2023.2-ubuntu-jammy
      replicas: 2
  glance:
    api:
      image: kolla/glance-api:2023.2-ubuntu-jammy
    backends:
    - name: ssd
      pvc:
        capacity: 100Gi
        storageClass: ceph-block-ssd
  placement:
    api:
      image: kolla/placement-api:2023.2-ubuntu-jammy
  nova:
    image: ghcr.io/ianunruh/openstack-operator-images/nova:master
    cells:
    - name: cell1
      compute:
        default:
          libvirtd:
            image: ghcr.io/ianunruh/openstack-operator-images/libvirt:master
  neutron:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
  ovn:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
    ovsdbNorth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
    ovsdbSouth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
  horizon:
    server:
      image: kolla/horizon:2023.2-ubuntu-jammy
