apiVersion: openstack.ospk8s.com/v1beta1
kind: NovaCompute
metadata:
  name: nova-cell1-default
spec:
  cell: cell1
  libvirtd:
    image: ghcr.io/ianunruh/openstack-operator-images/libvirt:master
  nodeSelector:
    openstack/compute-node: enabled
