apiVersion: openstack.ospk8s.com/v1beta1
kind: NovaComputeSet
metadata:
  name: nova-cell1-default
spec:
  cell: cell1
  image: kolla/nova-compute:2023.2-ubuntu-jammy
  libvirtd:
    image: kolla/nova-libvirt:2023.2-ubuntu-jammy
  ssh:
    image: kolla/nova-ssh:2023.2-ubuntu-jammy
  nodeSelector:
    openstack/cloud: openstack
    openstack/compute-node: enabled
