apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Neutron
metadata:
  name: neutron
spec:
  image: registry.kcloud.zone/ops/neutron:9b559abf
  server:
    replicas: 2
    ingress:
      host: neutron.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: neutron
    secret: neutron-db
    cluster: mariadb
  broker:
    name: neutron
    secret: neutron-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
