apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  image: registry.kcloud.zone/ops/glance:286f670e
  api:
    replicas: 2
    ingress:
      host: glance.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: glance
    secret: glance-db
    cluster: mariadb
  storage:
    volume:
      capacity: 100Gi
      storageClass: ceph-fs-ssd
      accessModes: [ReadWriteMany]
