apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack2.kcloud.zone
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    secret: mariadb
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
