apiVersion: openstack.ospk8s.com/v1beta1
kind: Horizon
metadata:
  name: horizon
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/horizon:master
  server:
    replicas: 2
    ingress:
      host: horizon.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  sso:
    enabled: true
    methods:
    - kind: openid
      title: OpenID Connect
    - kind: credentials
      title: Keystone Credentials
      default: true
