apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Senlin
metadata:
  name: senlin
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/senlin:master
  api:
    replicas: 2
    ingress:
      host: senlin.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  engine:
    replicas: 2
  database:
    name: senlin
    secret: senlin-db
    cluster: mariadb
  broker:
    name: senlin
    secret: senlin-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
