apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Cinder
metadata:
  name: cinder
spec:
  image: registry.kcloud.zone/ops/cinder:f07a994f
  api:
    replicas: 2
    ingress:
      host: cinder.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduler:
    replicas: 2
  volume:
    replicas: 2
    storage:
      rookCeph:
        namespace: rook-ceph
        clientName: openstack-cinder
        secret: cinder-ceph
        poolName: openstack-cinder-volumes
        deviceClass: ssd
        replicatedSize: 2
  database:
    name: cinder
    secret: cinder-db
    cluster: mariadb
  broker:
    name: cinder
    secret: cinder-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
