apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.k8s.example.com
  ingress:
    annotations:
      external-dns/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: ghcr.io/ianunruh/openstack-operator-images/keystone:master
    api:
      replicas: 2
    database:
      name: keystone
      secret: keystone-db
      cluster: mariadb
    broker:
      name: keystone
      secret: keystone-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  glance:
    image: ghcr.io/ianunruh/openstack-operator-images/glance:master
    database:
      name: glance
      secret: glance-db
      cluster: mariadb
    backends:
    - name: ssd
      pvc:
        capacity: 100Gi
        storageClass: ceph-fs-ssd
        accessModes: [ReadWriteMany]
  placement:
    image: ghcr.io/ianunruh/openstack-operator-images/placement:master
    database:
      name: placement
      secret: placement-db
      cluster: mariadb
  nova:
    image: ghcr.io/ianunruh/openstack-operator-images/nova:master
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-cell1-db
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
    libvirtd:
      image: ghcr.io/ianunruh/openstack-operator-images/libvirt:master
    compute:
      nodeSelector:
        openstack/cloud: openstack
        openstack/compute-node: enabled
    apiDatabase:
      name: nova_api
      secret: nova-api-db
      cluster: mariadb
    cellDatabase:
      name: nova_cell0
      secret: nova-cell0-db
      cluster: mariadb
    broker:
      name: nova
      secret: nova-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  neutron:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/compute-node: enabled
    database:
      name: neutron
      secret: neutron-db
      cluster: mariadb
    broker:
      name: neutron
      secret: neutron-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  ovn:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
    node:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-agent: ovn
    ovsdbNorth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
    ovsdbSouth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
  horizon:
    image: ghcr.io/ianunruh/openstack-operator-images/horizon:master
