apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Horizon
metadata:
  name: horizon
spec:
  image: registry.kcloud.zone/ops/horizon:af7b46c8
  server:
    replicas: 2
    ingress:
      host: horizon.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
