apiVersion: openstack.ospk8s.com/v1beta1
kind: Nova
metadata:
  name: nova
spec:
  api:
    image: kolla/nova-api:2023.2-ubuntu-jammy
    replicas: 2
    ingress:
      host: nova.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  conductor:
    image: kolla/nova-conductor:2023.2-ubuntu-jammy
    replicas: 2
  scheduler:
    image: kolla/nova-scheduler:2023.2-ubuntu-jammy
    replicas: 2
  apiDatabase:
    name: nova_api
    secret: nova-api-db
    cluster: mariadb
  cellDatabase:
    name: nova_cell0
    secret: nova-cell0-db
    cluster: mariadb
  broker:
    name: nova
    secret: nova-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
  cells:
  - name: cell1
    compute:
      default:
        nodeSelector:
          openstack/compute-node: enabled
    database:
      name: nova_cell1
      secret: nova-cell1-db
      cluster: mariadb
    broker:
      name: nova-cell1
      secret: nova-cell1-rabbitmq
      cluster: rabbitmq
      virtualHost: nova-cell1
