apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Magnum
metadata:
  name: magnum
spec:
  image: ianunruh/magnum:latest
  api:
    replicas: 2
    ingress:
      host: magnum.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  conductor:
    replicas: 1
  database:
    name: magnum
    secret: magnum-db
    cluster: mariadb
  broker:
    name: magnum
    secret: magnum-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
