apiVersion: openstack.ospk8s.com/v1beta1
kind: Magnum
metadata:
  name: magnum
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/magnum:master
  api:
    replicas: 2
    ingress:
      host: magnum.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  conductor:
    replicas: 1
  database:
    name: magnum
    secret: magnum-db
    cluster: mariadb
  broker:
    name: magnum
    secret: magnum-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
