apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Memcached
metadata:
  name: memcached
spec:
  image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
  volume:
    capacity: 50Gi
    storageClass: ceph-block-ssd
