apiVersion: openstack.ospk8s.com/v1beta1
kind: Manila
metadata:
  name: manila
spec:
  api:
    image: kolla/manila-api:2023.2-ubuntu-jammy
    replicas: 2
    ingress:
      host: manila.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduler:
    image: kolla/manila-scheduler:2023.2-ubuntu-jammy
    replicas: 1
  share:
    image: kolla/manila-share:2023.2-ubuntu-jammy
  backends:
  - name: cephfs
    shareBackendName: cephfs
    ceph:
      clientName: openstack-manila
      secret: manila-ceph
      rook:
        namespace: rook-ceph
  database:
    name: manila
    secret: manila-db
    cluster: mariadb
  broker:
    name: manila
    secret: manila-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
