apiVersion: openstack.ospk8s.com/v1beta1
kind: Rally
metadata:
  name: rally
spec:
  image: xrally/xrally-openstack:3.0.0
  data:
    capacity: 20Gi
    storageClass: ceph-block-ssd
  database:
    name: rally
    secret: rally-db
    cluster: mariadb
