apiVersion: openstack.ospk8s.com/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/heat:master
  api:
    replicas: 2
    ingress:
      host: heat.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  cfn:
    replicas: 2
    ingress:
      host: heat-cfn.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  engine:
    replicas: 2
  database:
    name: heat
    secret: heat-db
    cluster: mariadb
  broker:
    name: heat
    secret: heat-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
