apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: NovaCell
metadata:
  name: nova-cell1
spec:
  name: cell1
  compute:
    nodeSelector:
      openstack/compute-node: enabled
  libvirtd:
    image: ghcr.io/ianunruh/openstack-operator-images/libvirtd:master
  broker:
    name: nova-cell1
    secret: nova-cell1-rabbitmq
    cluster: rabbitmq
    virtualHost: nova-cell1
  database:
    name: nova_cell1
    secret: nova-cell1-db
    cluster: mariadb
  conductor:
    replicas: 2
  metadata:
    replicas: 2
  novncproxy:
    replicas: 2
    ingress:
      host: novnc.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
