apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Barbican
metadata:
  name: barbican
spec:
  image: ianunruh/barbican:latest
  api:
    replicas: 2
    ingress:
      host: barbican.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  worker:
    replicas: 2
  database:
    name: barbican
    secret: barbican-db
    cluster: mariadb
  broker:
    name: barbican
    secret: barbican-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
