apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: NovaCell
metadata:
  name: nova-cell1
spec:
  conductor:
    replicas: 2
  metadata:
    replicas: 2
  novncproxy:
    replicas: 2
    ingress:
      host: novnc.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
