apiVersion: openstack.ospk8s.com/v1beta1
kind: OVNControlPlane
metadata:
  name: ovn
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
  node:
    nodeSelector:
      openstack/network-agent: ovn
    bridgeMappings:
    - external:br-ex
    bridgePorts:
    - br-ex:vlan3000
  ovsdbNorth:
    volume:
      capacity: 20Gi
      storageClass: ceph-block-ssd
  ovsdbSouth:
    volume:
      capacity: 20Gi
      storageClass: ceph-block-ssd
