apiVersion: openstack.ospk8s.com/v1beta1
kind: Placement
metadata:
  name: placement
spec:
  image: kolla/placement-api:2023.2-ubuntu-jammy
  api:
    replicas: 2
    ingress:
      host: placement.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: placement
    secret: placement-db
    cluster: mariadb
