apiVersion: openstack.ospk8s.com/v1beta1
kind: MariaDB
metadata:
  name: mariadb
spec:
  image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
  volume:
    capacity: 50Gi
    storageClass: ceph-block-ssd
  prometheus:
    exporter:
      image: bitnami/mysqld-exporter:0.13.0
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    serviceMonitor: true
