apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: OVNControlPlane
metadata:
  name: ovn
spec:
  image: registry.kcloud.io/kcloud/openstack-operator-images/neutron:b6bd70b335eacf263f46b297672607bca24459cb
  node:
    nodeSelector:
      openstack/network-agent: ovn
    bridgeMappings:
    - external:br-ex
    bridgePorts:
    - br-ex:vlan3000
  ovsdbNorth:
    volume:
      capacity: 20Gi
      storageClass: ceph-block-ssd
  ovsdbSouth:
    volume:
      capacity: 20Gi
      storageClass: ceph-block-ssd
