apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Nova
metadata:
  name: nova
spec:
  image: ianunruh/nova:latest
  api:
    replicas: 2
    ingress:
      host: nova.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduler:
    replicas: 2
  libvirtd:
    image: ianunruh/libvirtd:latest
  compute:
    nodeSelector:
      openstack/compute-node: enabled
  apiDatabase:
    name: nova_api
    secret: nova-db-api
    cluster: mariadb
  cellDatabase:
    name: nova_cell0
    secret: nova-db-cell0
    cluster: mariadb
  broker:
    name: nova
    secret: nova-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
  cells:
  - name: cell1
    broker:
      name: nova-cell1
      secret: nova-cell1-rabbitmq
      cluster: rabbitmq
      virtualHost: nova-cell1
