apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Nova
metadata:
  name: nova
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/nova:master
  api:
    replicas: 2
    ingress:
      host: nova.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduler:
    replicas: 2
  apiDatabase:
    name: nova_api
    secret: nova-api-db
    cluster: mariadb
  cellDatabase:
    name: nova_cell0
    secret: nova-cell0-db
    cluster: mariadb
  broker:
    name: nova
    secret: nova-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
  cells:
  - name: cell1
    compute:
      nodeSelector:
        openstack/compute-node: enabled
    libvirtd:
      image: ghcr.io/ianunruh/openstack-operator-images/libvirtd:master
    database:
      name: nova_cell1
      secret: nova-cell1-db
      cluster: mariadb
    broker:
      name: nova-cell1
      secret: nova-cell1-rabbitmq
      cluster: rabbitmq
      virtualHost: nova-cell1
