apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Neutron
metadata:
  name: neutron
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
  server:
    replicas: 2
    ingress:
      host: neutron.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  metadataAgent:
    nodeSelector:
      openstack/network-node: enabled
  database:
    name: neutron
    secret: neutron-db
    cluster: mariadb
  broker:
    name: neutron
    secret: neutron-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
