apiVersion: openstack.ospk8s.com/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/glance:master
  api:
    replicas: 2
    ingress:
      host: glance.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: glance
    secret: glance-db
    cluster: mariadb
  backends:
  - name: ssd
    pvc:
      capacity: 100Gi
      storageClass: ceph-fs-ssd
      accessModes: [ReadWriteMany]
