apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  image: ianunruh/octavia:latest
  api:
    replicas: 2
    ingress:
      host: octavia.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  amphora:
    imageURL: https://tarballs.opendev.org/openstack/octavia/test-images/test-only-amphora-x64-haproxy-ubuntu-focal.qcow2
  api:
    replicas: 2
    ingress:
      host: octavia.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  healthManager:
    nodeSelector:
      openstack/network-node: enabled
  housekeeping:
    replicas: 1
  worker:
    replicas: 1
  database:
    name: octavia
    secret: octavia-db
    cluster: mariadb
  broker:
    name: octavia
    secret: octavia-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
