apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Cinder
metadata:
  name: cinder
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/cinder:master
  api:
    replicas: 2
    ingress:
      host: cinder.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  scheduler:
    replicas: 2
  backends:
  - name: ceph-ssd
    volumeBackendName: ceph-ssd
    ceph:
      poolName: openstack-cinder-volumes
      clientName: openstack-cinder
      secret: cinder-ceph
      rook:
        namespace: rook-ceph
        deviceClass: ssd
        replicatedSize: 2
  database:
    name: cinder
    secret: cinder-db
    cluster: mariadb
  broker:
    name: cinder
    secret: cinder-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
