apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.k8s.example.com
  ingress:
    annotations:
      external-dns/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
  nodeSelector:
    compute:
      openstack/cloud: openstack
      openstack/compute-node: enabled
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: ghcr.io/ianunruh/openstack-operator-images/keystone:master
    api:
      replicas: 2
  glance:
    image: ghcr.io/ianunruh/openstack-operator-images/glance:master
    backends:
    - name: ssd
      pvc:
        capacity: 100Gi
        storageClass: ceph-fs-ssd
        accessModes: [ReadWriteMany]
  placement:
    image: ghcr.io/ianunruh/openstack-operator-images/placement:master
  nova:
    image: ghcr.io/ianunruh/openstack-operator-images/nova:master
    cells:
    - name: cell1
      libvirtd:
        image: ghcr.io/ianunruh/openstack-operator-images/libvirt:master
  neutron:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
  ovn:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:master
    ovsdbNorth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
    ovsdbSouth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
  horizon:
    image: ghcr.io/ianunruh/openstack-operator-images/horizon:master
