apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  image: ianunruh/heat:latest
  api:
    replicas: 2
    ingress:
      host: heat.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  cfn:
    replicas: 2
    ingress:
      host: heat-cfn.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  engine:
    replicas: 2
  database:
    name: heat
    secret: heat-db
    cluster: mariadb
  broker:
    name: heat
    secret: heat-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
