apiVersion: openstack.ospk8s.com/v1beta1
kind: Senlin
metadata:
  name: senlin
spec:
  image: kolla/senlin-api:2023.2-ubuntu-jammy
  api:
    replicas: 2
    ingress:
      host: senlin.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  conductor:
    replicas: 2
  engine:
    replicas: 2
  healthManager:
    replicas: 2
  database:
    name: senlin
    secret: senlin-db
    cluster: mariadb
  broker:
    name: senlin
    secret: senlin-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
