apiVersion: openstack.ospk8s.com/v1beta1
kind: Keystone
metadata:
  name: keystone
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/keystone:master
  api:
    replicas: 2
    ingress:
      host: keystone.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: keystone
    secret: keystone-db
    cluster: mariadb
  broker:
    name: keystone
    secret: keystone-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
  notifications:
    enabled: true
  oidc:
    enabled: true
    identityProvider: gitlab
    dashboardURL: https://horizon.openstack.k8s.example.com/horizon/auth/websso/
    providerMetadataURL: https://accounts.google.com/.well-known/openid-configuration
    redirectURI: https://keystone.openstack.k8s.example.com/v3/OS-FEDERATION/identity_providers/gitlab/protocols/openid/auth
    secret: keystone-oidc
