apiVersion: openstack.ospk8s.com/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/octavia:master
  amphora:
    imageURL: https://tarballs.opendev.org/openstack/octavia/test-images/test-only-amphora-x64-haproxy-ubuntu-focal.qcow2
    managementCIDR: 192.168.250.0/24
  api:
    replicas: 2
    ingress:
      host: octavia.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  healthManager:
    nodeSelector:
      openstack/octavia-controller: enabled
  housekeeping:
    nodeSelector:
      openstack/octavia-controller: enabled
  worker:
    nodeSelector:
      openstack/octavia-controller: enabled
  database:
    name: octavia
    secret: octavia-db
    cluster: mariadb
  broker:
    name: octavia
    secret: octavia-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
