apiVersion: openstack.ospk8s.com/v1beta1
kind: Heat
metadata:
  name: heat
spec:
  api:
    image: kolla/heat-api:2023.2-ubuntu-jammy
    replicas: 2
    ingress:
      host: heat.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  cfn:
    image: kolla/heat-api-cfn:2023.2-ubuntu-jammy
    replicas: 2
    ingress:
      host: heat-cfn.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  engine:
    image: kolla/heat-engine:2023.2-ubuntu-jammy
    replicas: 2
  database:
    name: heat
    secret: heat-db
    cluster: mariadb
  broker:
    name: heat
    secret: heat-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
