apiVersion: openstack.ospk8s.com/v1beta1
kind: Barbican
metadata:
  name: barbican
spec:
  image: ghcr.io/ianunruh/openstack-operator-images/barbican:master
  api:
    replicas: 2
    ingress:
      host: barbican.openstack.k8s.example.com
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  worker:
    replicas: 2
  database:
    name: barbican
    secret: barbican-db
    cluster: mariadb
  broker:
    name: barbican
    secret: barbican-rabbitmq
    cluster: rabbitmq
    virtualHost: openstack
