apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: Placement
metadata:
  name: placement
spec:
  image: ianunruh/placement:latest
  api:
    replicas: 2
    ingress:
      host: placement.openstack2.kcloud.zone
      annotations:
        external-dns/enabled: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
  database:
    name: placement
    secret: placement-db
    cluster: mariadb
