apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack2.kcloud.zone
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: registry.kcloud.zone/ops/keystone:37a47821
    api:
      ingress:
        host: keystone.openstack2.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: keystone
      secret: keystone-db
      cluster: mariadb
  glance:
    image: registry.kcloud.zone/ops/glance:286f670e
    api:
      ingress:
        host: glance.openstack2.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: glance
      secret: glance-db
      cluster: mariadb
  placement:
    image: registry.kcloud.zone/ops/placement:d8f1ff3a
    api:
      ingress:
        host: placement.openstack2.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: placement
      secret: placement-db
      cluster: mariadb

