apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}
spec:
  endpoints:
  - port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: {{ .Name }}
