apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.k8s.example.com
  ingress:
    annotations:
      external-dns/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: ghcr.io/ianunruh/openstack-operator-images/keystone:latest
    database:
      name: keystone
      secret: keystone-db
      cluster: mariadb
    broker:
      name: keystone
      secret: keystone-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  glance:
    image: ghcr.io/ianunruh/openstack-operator-images/glance:latest
    database:
      name: glance
      secret: glance-db
      cluster: mariadb
    backends:
    - name: ceph-ssd
      ceph:
        poolName: openstack-glance-images
        clientName: openstack-glance
        secret: glance-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  cinder:
    image: ghcr.io/ianunruh/openstack-operator-images/cinder:latest
    backends:
    - name: ceph
      volumeBackendName: ceph
      ceph:
        poolName: openstack-cinder-volumes
        clientName: openstack-cinder
        secret: cinder-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
    database:
      name: cinder
      secret: cinder-db
      cluster: mariadb
    broker:
      name: cinder
      secret: cinder-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  placement:
    image: ghcr.io/ianunruh/openstack-operator-images/placement:latest
    database:
      name: placement
      secret: placement-db
      cluster: mariadb
  nova:
    image: ghcr.io/ianunruh/openstack-operator-images/nova:latest
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-db-cell1
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
    libvirtd:
      image: ghcr.io/ianunruh/openstack-operator-images/libvirtd:latest
    compute:
      nodeSelector:
        openstack/cloud: openstack
        openstack/compute-node: enabled
    apiDatabase:
      name: nova_api
      secret: nova-db-api
      cluster: mariadb
    cellDatabase:
      name: nova_cell0
      secret: nova-db-cell0
      cluster: mariadb
    broker:
      name: nova
      secret: nova-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  neutron:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:latest
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-node: enabled
    database:
      name: neutron
      secret: neutron-db
      cluster: mariadb
    broker:
      name: neutron
      secret: neutron-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  ovn:
    image: ghcr.io/ianunruh/openstack-operator-images/neutron:latest
    node:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-agent: ovn
    ovsdbNorth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
    ovsdbSouth:
      volume:
        capacity: 20Gi
        storageClass: ceph-block-ssd
  horizon:
    image: ghcr.io/ianunruh/openstack-operator-images/horizon:latest
  heat:
    image: ghcr.io/ianunruh/openstack-operator-images/heat:latest
    database:
      name: heat
      secret: heat-db
      cluster: mariadb
    broker:
      name: heat
      secret: heat-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  magnum:
    image: ghcr.io/ianunruh/openstack-operator-images/magnum:latest
    database:
      name: magnum
      secret: magnum-db
      cluster: mariadb
    broker:
      name: magnum
      secret: magnum-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  barbican:
    image: ghcr.io/ianunruh/openstack-operator-images/barbican:latest
    database:
      name: barbican
      secret: barbican-db
      cluster: mariadb
    broker:
      name: barbican
      secret: barbican-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
