apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.kcloud.zone
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: registry.kcloud.zone/ops/keystone:37a47821
    api:
      ingress:
        host: keystone.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: keystone
      secret: keystone-db
      cluster: mariadb
  glance:
    image: registry.kcloud.zone/ops/glance:286f670e
    api:
      ingress:
        host: glance.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
    database:
      name: glance
      secret: glance-db
      cluster: mariadb
  cinder:
    image: registry.kcloud.zone/ops/cinder:f07a994f
    api:
      ingress:
        host: cinder.openstack2.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: cinder
      secret: cinder-db
      cluster: mariadb
    broker:
      name: cinder
      secret: cinder-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  placement:
    image: registry.kcloud.zone/ops/placement:d8f1ff3a
    api:
      ingress:
        host: placement.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    database:
      name: placement
      secret: placement-db
      cluster: mariadb
  nova:
    image: registry.kcloud.zone/ops/nova:3173da3b
    api:
      ingress:
        host: nova.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-db-cell1
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
      novncproxy:
        ingress:
          host: novnc.openstack.kcloud.zone
          annotations:
            external-dns/enabled: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
    libvirtd:
      image: registry.kcloud.zone/ops/libvirt:4495c89d
    compute:
      nodeSelector:
        openstack/compute-node: enabled
    apiDatabase:
      name: nova_api
      secret: nova-db-api
      cluster: mariadb
    cellDatabase:
      name: nova_cell0
      secret: nova-db-cell0
      cluster: mariadb
    broker:
      name: nova
      secret: nova-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  neutron:
    image: registry.kcloud.zone/ops/neutron:9b559abf
    server:
      ingress:
        host: neutron.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
    linuxBridgeAgent:
      nodeSelector:
        openstack/network-agent: linuxbridge
    dhcpAgent:
      nodeSelector:
        openstack/network-node: enabled
    l3Agent:
      nodeSelector:
        openstack/network-node: enabled
    metadataAgent:
      nodeSelector:
        openstack/network-node: enabled
    database:
      name: neutron
      secret: neutron-db
      cluster: mariadb
    broker:
      name: neutron
      secret: neutron-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  horizon:
    image: registry.kcloud.zone/ops/horizon:af7b46c8
    server:
      ingress:
        host: horizon.openstack.kcloud.zone
        annotations:
          external-dns/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"

