apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack.kcloud.zone
  ingress:
    annotations:
      external-dns/enabled: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
  broker:
    image: docker.io/bitnami/rabbitmq:3.8.9-debian-10-r58
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  cache:
    image: docker.io/bitnami/memcached:1.6.9-debian-10-r0
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  database:
    image: docker.io/bitnami/mariadb:10.5.8-debian-10-r21
    volume:
      capacity: 50Gi
      storageClass: ceph-block-ssd
  keystone:
    image: ianunruh/keystone:latest
    database:
      name: keystone
      secret: keystone-db
      cluster: mariadb
  glance:
    image: ianunruh/glance:latest
    database:
      name: glance
      secret: glance-db
      cluster: mariadb
    storage:
      rookCeph:
        namespace: rook-ceph
        clientName: openstack-glance
        secret: glance-ceph
        poolName: openstack-glance-images
        deviceClass: ssd
        replicatedSize: 2
  cinder:
    image: ianunruh/cinder:latest
    volume:
      storage:
        rookCeph:
          namespace: rook-ceph
          clientName: openstack-cinder
          secret: cinder-ceph
          poolName: openstack-cinder-volumes
          deviceClass: ssd
          replicatedSize: 2
    database:
      name: cinder
      secret: cinder-db
      cluster: mariadb
    broker:
      name: cinder
      secret: cinder-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  placement:
    image: ianunruh/placement:latest
    database:
      name: placement
      secret: placement-db
      cluster: mariadb
  nova:
    image: ianunruh/nova:latest
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-db-cell1
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
    libvirtd:
      image: ianunruh/libvirtd:latest
    compute:
      nodeSelector:
        openstack/cloud: openstack
        openstack/compute-node: enabled
    apiDatabase:
      name: nova_api
      secret: nova-db-api
      cluster: mariadb
    cellDatabase:
      name: nova_cell0
      secret: nova-db-cell0
      cluster: mariadb
    broker:
      name: nova
      secret: nova-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  neutron:
    image: ianunruh/neutron:latest
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-agent: linuxbridge
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-node: enabled
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-node: enabled
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack
        openstack/network-node: enabled
    database:
      name: neutron
      secret: neutron-db
      cluster: mariadb
    broker:
      name: neutron
      secret: neutron-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
  horizon:
    image: ianunruh/horizon:latest
  heat:
    image: ianunruh/heat:latest
    database:
      name: heat
      secret: heat-db
      cluster: mariadb
    broker:
      name: heat
      secret: heat-rabbitmq
      cluster: rabbitmq
      virtualHost: openstack
