apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack2.kcloud.zone
  keystone:
    api:
      ingress:
        host: keystone.openstack2.kcloud.zone
  glance:
    api:
      ingress:
        host: glance.openstack2.kcloud.zone
  cinder:
    api:
      ingress:
        host: cinder.openstack2.kcloud.zone
  placement:
    api:
      ingress:
        host: placement.openstack2.kcloud.zone
  nova:
    api:
      ingress:
        host: nova.openstack2.kcloud.zone
    compute:
      nodeSelector:
        openstack/cloud: openstack2
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-db-cell1
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
      novncproxy:
        ingress:
          host: novnc.openstack2.kcloud.zone
          annotations:
            external-dns/enabled: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
  neutron:
    server:
      ingress:
        host: neutron.openstack2.kcloud.zone
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack2
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack2
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack2
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack2
  horizon:
    server:
      ingress:
        host: horizon.openstack2.kcloud.zone
