apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack2.kcloud.zone
  cinder:
    backends:
    - name: ceph
      volumeBackendName: ceph
      ceph:
        poolName: openstack2-cinder-volumes
        clientName: openstack2-cinder
        secret: cinder-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  glance:
    backends:
    - name: ceph-ssd
      ceph:
        poolName: openstack2-glance-images
        clientName: openstack2-glance
        secret: glance-ceph
        rook:
          namespace: rook-ceph
          deviceClass: ssd
          replicatedSize: 2
  nova:
    compute:
      nodeSelector:
        openstack/cloud: openstack2
  neutron:
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack2
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack2
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack2
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack2
