apiVersion: openstack.k8s.ianunruh.com/v1beta1
kind: ControlPlane
metadata:
  name: default
spec:
  domain: openstack2.kcloud.zone
  nova:
    compute:
      nodeSelector:
        openstack/cloud: openstack2
    cells:
    - name: cell1
      database:
        name: nova_cell1
        secret: nova-db-cell1
        cluster: mariadb
      broker:
        name: nova-cell1
        secret: nova-cell1-rabbitmq
        cluster: rabbitmq
        virtualHost: nova-cell1
  neutron:
    linuxBridgeAgent:
      nodeSelector:
        openstack/cloud: openstack2
    dhcpAgent:
      nodeSelector:
        openstack/cloud: openstack2
    l3Agent:
      nodeSelector:
        openstack/cloud: openstack2
    metadataAgent:
      nodeSelector:
        openstack/cloud: openstack2
