---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  isCA: {{ .IsCA }}
  commonName: {{ .Name }}
  dnsNames: [{{ StringsJoin .DNSNames ", " }}]
  secretName: {{ .SecretName }}
  usages: [{{ StringsJoin .Usages ", " }}]
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .IssuerName }}
    kind: {{ .IssuerKind }}
    group: cert-manager.io
