#!/bin/bash
set -eu

mysql -u $DATABASE_ADMIN_USER <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
CREATE USER IF NOT EXISTS $DATABASE_NAME@'%' IDENTIFIED BY '$DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO $DATABASE_NAME@'%';
EOF
