# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/openstack.k8s.ianunruh.com_controlplanes.yaml
- bases/openstack.k8s.ianunruh.com_mariadbs.yaml
- bases/openstack.k8s.ianunruh.com_mariadbdatabases.yaml
- bases/openstack.k8s.ianunruh.com_keystones.yaml
- bases/openstack.k8s.ianunruh.com_keystoneservices.yaml
- bases/openstack.k8s.ianunruh.com_keystoneusers.yaml
- bases/openstack.k8s.ianunruh.com_glances.yaml
- bases/openstack.k8s.ianunruh.com_placements.yaml
- bases/openstack.k8s.ianunruh.com_rabbitmqs.yaml
- bases/openstack.k8s.ianunruh.com_rabbitmqusers.yaml
- bases/openstack.k8s.ianunruh.com_novas.yaml
- bases/openstack.k8s.ianunruh.com_novacells.yaml
- bases/openstack.k8s.ianunruh.com_neutrons.yaml
- bases/openstack.k8s.ianunruh.com_horizons.yaml
- bases/openstack.k8s.ianunruh.com_memcacheds.yaml
- bases/openstack.k8s.ianunruh.com_cinders.yaml
- bases/openstack.k8s.ianunruh.com_heats.yaml
- bases/openstack.k8s.ianunruh.com_magnums.yaml
- bases/openstack.k8s.ianunruh.com_barbicans.yaml
- bases/openstack.k8s.ianunruh.com_ovncontrolplanes.yaml
- bases/openstack.k8s.ianunruh.com_octavias.yaml
- bases/openstack.k8s.ianunruh.com_rallies.yaml
- bases/openstack.k8s.ianunruh.com_manilas.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_controlplanes.yaml
#- patches/webhook_in_mariadbs.yaml
#- patches/webhook_in_mariadbdatabases.yaml
- patches/webhook_in_keystones.yaml
#- patches/webhook_in_keystoneservices.yaml
#- patches/webhook_in_keystoneusers.yaml
#- patches/webhook_in_glances.yaml
#- patches/webhook_in_placements.yaml
#- patches/webhook_in_rabbitmqs.yaml
#- patches/webhook_in_rabbitmqusers.yaml
#- patches/webhook_in_novas.yaml
#- patches/webhook_in_novacells.yaml
#- patches/webhook_in_neutrons.yaml
#- patches/webhook_in_horizons.yaml
#- patches/webhook_in_memcacheds.yaml
#- patches/webhook_in_cinders.yaml
#- patches/webhook_in_heats.yaml
#- patches/webhook_in_magnums.yaml
#- patches/webhook_in_barbicans.yaml
#- patches/webhook_in_ovncontrolplanes.yaml
#- patches/webhook_in_octavias.yaml
#- patches/webhook_in_rallies.yaml
#- patches/webhook_in_manilas.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_controlplanes.yaml
#- patches/cainjection_in_mariadbs.yaml
#- patches/cainjection_in_mariadbdatabases.yaml
- patches/cainjection_in_keystones.yaml
#- patches/cainjection_in_keystoneservices.yaml
#- patches/cainjection_in_keystoneusers.yaml
#- patches/cainjection_in_glances.yaml
#- patches/cainjection_in_placements.yaml
#- patches/cainjection_in_rabbitmqs.yaml
#- patches/cainjection_in_rabbitmqusers.yaml
#- patches/cainjection_in_novas.yaml
#- patches/cainjection_in_novacells.yaml
#- patches/cainjection_in_neutrons.yaml
#- patches/cainjection_in_horizons.yaml
#- patches/cainjection_in_memcacheds.yaml
#- patches/cainjection_in_cinders.yaml
#- patches/cainjection_in_heats.yaml
#- patches/cainjection_in_magnums.yaml
#- patches/cainjection_in_barbicans.yaml
#- patches/cainjection_in_ovncontrolplanes.yaml
#- patches/cainjection_in_octavias.yaml
#- patches/cainjection_in_rallies.yaml
#- patches/cainjection_in_manilas.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
