# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/openstack.ospk8s.com_controlplanes.yaml
- bases/openstack.ospk8s.com_mariadbs.yaml
- bases/openstack.ospk8s.com_mariadbdatabases.yaml
- bases/openstack.ospk8s.com_keystones.yaml
- bases/openstack.ospk8s.com_keystoneservices.yaml
- bases/openstack.ospk8s.com_keystoneusers.yaml
- bases/openstack.ospk8s.com_glances.yaml
- bases/openstack.ospk8s.com_placements.yaml
- bases/openstack.ospk8s.com_rabbitmqs.yaml
- bases/openstack.ospk8s.com_rabbitmqusers.yaml
- bases/openstack.ospk8s.com_novas.yaml
- bases/openstack.ospk8s.com_novacells.yaml
- bases/openstack.ospk8s.com_neutrons.yaml
- bases/openstack.ospk8s.com_horizons.yaml
- bases/openstack.ospk8s.com_memcacheds.yaml
- bases/openstack.ospk8s.com_cinders.yaml
- bases/openstack.ospk8s.com_heats.yaml
- bases/openstack.ospk8s.com_magnums.yaml
- bases/openstack.ospk8s.com_barbicans.yaml
- bases/openstack.ospk8s.com_ovncontrolplanes.yaml
- bases/openstack.ospk8s.com_octavias.yaml
- bases/openstack.ospk8s.com_rallies.yaml
- bases/openstack.ospk8s.com_manilas.yaml
- bases/openstack.ospk8s.com_rallytasks.yaml
- bases/openstack.ospk8s.com_novahostaggregates.yaml
- bases/openstack.ospk8s.com_novakeypairs.yaml
- bases/openstack.ospk8s.com_novaflavors.yaml
- bases/openstack.ospk8s.com_novacomputesets.yaml
- bases/openstack.ospk8s.com_novacomputenodes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_controlplanes.yaml
#- path: patches/webhook_in_mariadbs.yaml
#- path: patches/webhook_in_mariadbdatabases.yaml
#- path: patches/webhook_in_keystones.yaml
#- path: patches/webhook_in_keystoneservices.yaml
#- path: patches/webhook_in_keystoneusers.yaml
#- path: patches/webhook_in_glances.yaml
#- path: patches/webhook_in_placements.yaml
#- path: patches/webhook_in_rabbitmqs.yaml
#- path: patches/webhook_in_rabbitmqusers.yaml
#- path: patches/webhook_in_novas.yaml
#- path: patches/webhook_in_novacells.yaml
#- path: patches/webhook_in_neutrons.yaml
#- path: patches/webhook_in_horizons.yaml
#- path: patches/webhook_in_memcacheds.yaml
#- path: patches/webhook_in_cinders.yaml
#- path: patches/webhook_in_heats.yaml
#- path: patches/webhook_in_magnums.yaml
#- path: patches/webhook_in_barbicans.yaml
#- path: patches/webhook_in_ovncontrolplanes.yaml
#- path: patches/webhook_in_octavias.yaml
#- path: patches/webhook_in_rallies.yaml
#- path: patches/webhook_in_manilas.yaml
#- path: patches/webhook_in_rallytasks.yaml
#- path: patches/webhook_in_novahostaggregates.yaml
#- path: patches/webhook_in_novakeypairs.yaml
#- path: patches/webhook_in_novaflavors.yaml
#- path: patches/webhook_in_novacomputesets.yaml
#- path: patches/webhook_in_novacomputenodes.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_controlplanes.yaml
- path: patches/cainjection_in_mariadbs.yaml
#- path: patches/cainjection_in_mariadbdatabases.yaml
- path: patches/cainjection_in_keystones.yaml
#- path: patches/cainjection_in_keystoneservices.yaml
- path: patches/cainjection_in_keystoneusers.yaml
- path: patches/cainjection_in_glances.yaml
- path: patches/cainjection_in_placements.yaml
- path: patches/cainjection_in_rabbitmqs.yaml
#- path: patches/cainjection_in_rabbitmqusers.yaml
- path: patches/cainjection_in_novas.yaml
- path: patches/cainjection_in_novacells.yaml
- path: patches/cainjection_in_neutrons.yaml
- path: patches/cainjection_in_horizons.yaml
- path: patches/cainjection_in_memcacheds.yaml
- path: patches/cainjection_in_cinders.yaml
- path: patches/cainjection_in_heats.yaml
- path: patches/cainjection_in_magnums.yaml
- path: patches/cainjection_in_barbicans.yaml
- path: patches/cainjection_in_ovncontrolplanes.yaml
- path: patches/cainjection_in_octavias.yaml
- path: patches/cainjection_in_rallies.yaml
- path: patches/cainjection_in_rallytasks.yaml
- path: patches/cainjection_in_manilas.yaml
#- path: patches/cainjection_in_novahostaggregates.yaml
#- path: patches/cainjection_in_novakeypairs.yaml
#- path: patches/cainjection_in_novaflavors.yaml
- path: patches/cainjection_in_novacomputesets.yaml
#- path: patches/cainjection_in_novacomputenodes.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
