name: Teardown GKE gate

on:
  pull_request:
    types: [closed]

env:
  CLUSTER_NAME: gate-pr-${{ github.event.pull_request.number }}
  CLOUDSDK_COMPUTE_ZONE: us-central1-a
  DNS_ZONE: ospk8s

jobs:
  setup:
    if: contains(github.event.pull_request.labels.*.name, 'gate')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mask service account key
        run: |
          echo "::add-mask::${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ospk8s
          service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}
          export_default_credentials: true

      - name: Teardown GKE cluster
        working-directory: gate/gke
        run: ./teardown.sh
