name: Teardown CAPI gate

on:
  pull_request:
    types: [closed]

env:
  CLUSTER_NAME: gate-pr-${{ github.event.pull_request.number }}
  OPENSTACK_FAILURE_DOMAIN: az3
  DNS_ZONE: ospk8s

jobs:
  setup:
    if: contains(github.event.pull_request.labels.*.name, 'gate-capi')

    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mask secrets
        run: |
          echo "::add-mask::${{ secrets.GATE_KUBECONFIG }}"
          echo "::add-mask::${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ospk8s
          service_account_key: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}
          export_default_credentials: true

      - name: Install tools
        working-directory: gate/capi
        run: ./install-tools.sh

      - name: Teardown CAPI cluster
        working-directory: gate/capi
        run: ./teardown.sh
        env:
          GATE_KUBECONFIG: ${{ secrets.GATE_KUBECONFIG }}
