name: Teardown GKE preview

on:
  pull_request:
    types: [closed]

env:
  CLUSTER_NAME: preview-pr-${{ github.event.pull_request.number }}
  CLOUDSDK_COMPUTE_ZONE: us-central1-a
  DNS_ZONE: ospk8s

jobs:
  teardown:
    if: contains(github.event.pull_request.labels.*.name, 'preview-gke')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask service account key
        run: |
          echo "::add-mask::${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}"

      - name: Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SVC_ACCOUNT_KEY_JSON }}
          project_id: ospk8s

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Teardown GKE cluster
        working-directory: ci/preview/gke
        run: ./teardown.sh
